### ISSUE TITLE
DAM integration - Can't upload/create/select/drop file 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/mcms-app#11]
Can't upload file 
![image](https://user-images.githubusercontent.com/44457418/210498805-b93e3664-9ca2-4f63-93b3-008445a10867.png)
Missing the overlay when user click on "Create file" button
The popup not center screen 
![image](https://user-images.githubusercontent.com/44457418/210499118-79a20acd-9137-493b-8acb-a76401cde1c3.png)
Can remove the text placeholder
![image](https://user-images.githubusercontent.com/44457418/210499424-fb9375a6-0482-4681-bc89-a17d7d415df6.png)
Can't create new file 
![image](https://user-images.githubusercontent.com/44457418/210499491-f97fd6fc-123c-447b-ab12-5dcc344bbc82.png)
The select/drop file is the same

**Comment by huynhngocgiau** [comment]
Upload/create/select/drop file work 

The popup not center screen 
![center screen](https://user-images.githubusercontent.com/79819354/215667205-a52af1c2-e1b6-4dac-9209-3f65c23a7ff6.png)

**Comment by VinhNguyenredWeb** [comment]
Anh @kakahuy113  please help me check this ticket ,thanks.

**Comment by kakahuy113** [comment]
it done e @VinhNguyenredWeb

**Comment by huynhngocgiau** [comment]
Don't updated
![image](https://user-images.githubusercontent.com/79819354/216502781-c7f4b463-633e-4c55-8017-a8ce2fb43ec5.png)
Create folder
![image](https://user-images.githubusercontent.com/79819354/216503164-542c972d-ec08-4143-a9e0-aaaac832ad48.png)
Upload/Select file
![image](https://user-images.githubusercontent.com/79819354/216503284-ef4ad2b8-b159-4694-b7b3-6e95046a9be3.png)
