### ISSUE TITLE
Image not show when re-render

### ISSUE THREAD

**Issue by GiaPhu811** [aesirxio/mcms-app#18]
![image](https://user-images.githubusercontent.com/106291216/210769366-9a090332-3783-4f86-a1dd-f5486b8dc96b.png)

After re-render:

![image](https://user-images.githubusercontent.com/106291216/210769650-5c9d629f-2b47-4652-852c-557a9eb1791b.png)

**Comment by VanTrieuThanh** [comment]
has fine for me on the dev branch 
![image](https://user-images.githubusercontent.com/44457418/211462714-7b2a0404-ff1a-4c74-abf8-e1faf83c60db.png)
