### ISSUE TITLE
Create Item/Category - make duplicate item when user click the "Save", "Save & Close" button more time 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/mcms-app#22]
1 create 1 item and click on the "Save" button 
2 message is success 
3 click again the button "Save" or "Save & Close" button 
Actual result: 
the Item will duplicate 
![image](https://user-images.githubusercontent.com/44457418/210972893-c4474a7a-8525-4da3-a0c8-5c20c437643a.png)

**Comment by NguyenBao10** [comment]
looks like you are calling API two time, i think we should block the button after the first click e @VinhNguyenredWeb

**Comment by VanTrieuThanh** [comment]
it still not update em @VinhNguyenredWeb ![image](https://user-images.githubusercontent.com/44457418/211495032-aafc9ca0-5313-4d29-aabb-23f957e644ea.png)

**Comment by VanTrieuThanh** [comment]
has fine on the demo site 
![image](https://user-images.githubusercontent.com/44457418/212615606-ab57dc51-2703-42e8-9dcf-d3bee50e7612.png)
![image](https://user-images.githubusercontent.com/44457418/212615688-66fad65b-ff4a-43b7-ba20-fd7ca100e802.png)
