### ISSUE TITLE
Dark mode 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/mcms-app#4]
The line at the header 
![image](https://user-images.githubusercontent.com/44457418/210481644-87294270-70cc-42a7-b325-aa6613d38a89.png)

Items page 
Missing search field 
Missing the amount item (Remove text "Create, edit, and manage the field group on your site")
Missing the filter 
The setup item not showing so can hide the Setup title
![image](https://user-images.githubusercontent.com/44457418/210476526-582de360-ca42-4eae-bc59-70078a861e1a.png)
column item 
![image](https://user-images.githubusercontent.com/44457418/210488056-d3f11af4-6a60-4682-ad23-dfe486d38072.png)
color text on tab 
![image](https://user-images.githubusercontent.com/44457418/210502365-d94867d9-c298-4151-b0fc-88fc7b512f31.png)

DAM page 
![image](https://user-images.githubusercontent.com/44457418/210481557-4e6b1cd7-8f8f-4795-949e-ab0e47179c8d.png)

DMA page 
![image](https://user-images.githubusercontent.com/44457418/210481488-3f28ef7b-1f27-4ddf-a69a-972b379f564a.png)

The Dropdown in header  
![image](https://user-images.githubusercontent.com/44457418/210481940-b5b5c488-2f9b-47b2-be78-ead325bac81b.png)

Login page 
![image](https://user-images.githubusercontent.com/44457418/210482045-f26eea1c-7121-4d97-87f1-d277a5fa9067.png)

Create item page 
Missing the active item when user going on 
background-color in Intro text
color "Select File" button
![image](https://user-images.githubusercontent.com/44457418/210482496-a5e07faa-bc31-4c93-9618-0cd33938d1e3.png)
missing icon image 
![image](https://user-images.githubusercontent.com/44457418/210495269-3df60b64-0087-4cef-a243-038b806c2247.png)

Create category page 
color "Select File" button
![image](https://user-images.githubusercontent.com/44457418/210482816-d12a5314-b704-4226-b4f7-537d98708175.png)

list item per page - has the light in this
![image](https://user-images.githubusercontent.com/44457418/210501578-7ea7e785-1e09-4995-bd74-5ce20b842fce.png)
Pagination - check the next/preview icon 
![image](https://user-images.githubusercontent.com/44457418/210501997-dcbe75d6-5f94-4e03-bef0-58a8b4aaca3b.png)

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/211477306-d3c9a74c-c95d-4a8c-819b-da6b1210020c.png)
![image](https://user-images.githubusercontent.com/44457418/211477359-ed86173c-0ef9-43c2-ada2-75ff66d9a6da.png)
![image](https://user-images.githubusercontent.com/44457418/211477651-b28c4f2c-9c15-4338-afa8-32f810475f45.png)
![image](https://user-images.githubusercontent.com/44457418/211477736-4941e6ee-7508-43d8-a8e6-59c7a05f6ec1.png)

**Comment by huynhngocgiau** [comment]
DMA page
![darkmode](https://user-images.githubusercontent.com/79819354/215695724-7045fcf6-202a-4274-aa62-6a96bef64a67.png)

Type item
![dark1](https://user-images.githubusercontent.com/79819354/215697376-d6aede11-077f-455d-990e-7d6f448333c1.png)

Sort By item
![dark2](https://user-images.githubusercontent.com/79819354/215697401-524b5bdc-3fe0-405b-9247-89af4dba6986.png)
Icon
![icon](https://user-images.githubusercontent.com/79819354/215697433-9be8e6b6-b9f0-4548-9cfb-fac09c0270a0.png)
![icon2](https://user-images.githubusercontent.com/79819354/215697449-c844b1cd-7462-4cc1-86c2-275882d1bed5.png)

**Comment by GiaPhu811** [comment]
It's DAM and DMA intergrate em @huynhngocgiau. Need to fix color in those app

**Comment by huynhngocgiau** [comment]
MCMS done
