### ISSUE TITLE
Message status - Change style

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/mcms-app#6]
![image](https://user-images.githubusercontent.com/44457418/210485521-dce99103-5132-493c-b839-ee1e253d9f52.png)
Design at 
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=552%3A1816&t=jdUBSTjC1zu0f0ws-0

**Comment by VanTrieuThanh** [comment]
Error message 
![image](https://user-images.githubusercontent.com/44457418/211506631-137ccbdf-13c1-4db0-ba11-8237b1724070.png)

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/211977781-565fe331-3405-4611-bb79-1634ad3707b4.png)
![image](https://user-images.githubusercontent.com/44457418/211977820-503cc192-a089-4098-bb43-8dbb2a15a862.png)
![image](https://user-images.githubusercontent.com/44457418/211977920-3023a58d-8a60-485e-86bb-7d9271894e0f.png)

**Comment by GiaPhu811** [comment]
We have new design so i will close this task
