### ISSUE TITLE
Validate errorr

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/mcms-app#65]
Create items -> Save -> Remove title -> Not show message error

https://user-images.githubusercontent.com/79819354/216502259-9a727c34-ab7d-4e2a-a3df-221fa76462e2.mp4

**Comment by lklong709** [comment]
QA: https://github.com/aesirxio/mcms-app/pull/80

**Comment by VanTrieuThanh** [comment]
Message has show on 
![image](https://user-images.githubusercontent.com/44457418/221487995-f3f5aef2-2d3b-4990-b046-76b68501861a.png)
