### ISSUE TITLE
Dissapear the menu when click on search

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/mcms-app#69]
1. Launch the app at local
2. Go to item
3. Click on search

Actual output:
Dissapear the menu when click on search

Expected output:
The menu is visable while the user is searching
![Image](https://user-images.githubusercontent.com/30283123/218987620-7ae2d6d1-8cc7-4a09-a486-289cf18a10cf.gif)

**Comment by lklong709** [comment]
PR: https://github.com/aesirxio/mcms-app/pull/83

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/221465612-75a98418-a72a-46fc-9175-57811cfc50d4.png)
