### ISSUE TITLE
Item list page - Hide field has hiden in detail page 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/mcms-app#7]
![image](https://user-images.githubusercontent.com/44457418/210487998-d07a5b9b-d89b-4fd8-b6e0-0b9514984e35.png)

**Comment by VinhNguyenredWeb** [comment]
Done @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
The field not content has remove
![image](https://user-images.githubusercontent.com/44457418/210950979-44d852de-0cc0-4a00-8602-a6c232a525b6.png)
