### ISSUE TITLE
Login - Remove Authentication Login

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/mcms-app#72]
https://github.com/aesirxio/dam-app/issues/215

**Comment by lklong709** [comment]
qa: https://github.com/aesirxio/mcms-app/pull/86

**Comment by huynhngocgiau** [comment]
Width button too long a @lklong709 
![image](https://user-images.githubusercontent.com/79819354/222706455-2494c8ab-297d-43c5-a8f8-ebb6fdc87314.png)

**Comment by VanTrieuThanh** [comment]
has update 
![image](https://user-images.githubusercontent.com/44457418/223662099-e608a64f-b505-4930-9b0a-1b20eb18eff0.png)
