### ISSUE TITLE
Missing profile item

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/mcms-app#81]
![image](https://user-images.githubusercontent.com/30283123/220822968-d6b90960-578b-4a44-a445-5f72c5f08c2d.png)
 Missing profile item

**Comment by lklong709** [comment]
QA PR: https://github.com/aesirxio/mcms-app/pull/84

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/221463457-ac9274e1-e4cf-40a5-bc04-cbcea4fd0528.png)
